language: python

python:
  - "3.7"
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
before_install:
  - export DJANGO_SETTINGS_MODULE=raspal.settings.travis
  
services:
  - postgresql

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
